### PR TITLE
reworked DirectControlLoop to fix custom values for "maxPwmChangePerCycle"

### LINKED ISSUE #326: maxPwmChangePerCycle buggy, keeps fan off
Thanks for picking up my PR and making the direct algo happen. I think i dis

**Describe the bug**
when using controlAlgorithm.direct.maxPwmChangePerCycle with any value, it wants to set the correct pwm value, but then sets the fan speed to zero instead.

As last time, i'll try to properly debug this when i find time, but right now, Stalker 2 was more important.

**To Reproduce**

config:
```yaml
fans:
  - id: myfan
    hwmon:
      platform: nct6792-isa-0290
      rpmChannel: 3
      pwmChannel: 3
    neverStop: true
    curve: topfans_curve
    controlAlgorithm:
        direct:
            maxPwmChangePerCycle: 10
    pwmMap:
      0: 0
      255: 255
```
I assume curve and sensor do not matter, use anything.

What happens is, Debug shows correct desired PWM, but actually set PWM is zero and fan stays off.
When just using direct without maxPwmChangePerCycle, it works as expected.

**Expected behavior**
As temp in curves are changing, target PWM is slowly approached

**Screenshots**

**Desktop (please complete the following information):**

- Distro: Arch
- `uname -a`: Linux xxx 6.11.9-arch1-1 1 SMP PREEMPT_DYNAMIC Sun, 17 Nov 2024 16:06:17 +0000 x86_64 GNU/Linux
- `sensors -v`:  sensors version 3.6.0+git with libsensors version 3.6.0+git
- `fan2go version`: 0.9.0

### PR DESCRIPTION
**Pull request by markusressel**
contributes to #326

### CODE REVIEW

File: internal/control_loop/direct.go [hunk 1]
```diff
@@ -31,27 +31,19 @@ func NewDirectControlLoop(
...
 	l.lastTime = loopTime
 
 	var stepTarget = float64(target)
 	if l.maxPwmChangePerCycle != nil {
-		// the pwm adjustment depends on the direction and
-		// the time-based change speed limit.
-		stepTarget = float64(*l.maxPwmChangePerCycle) * dt
+		maxChangeValue := *l.maxPwmChangePerCycle
+		// TODO: figure out how to normalize the change to the timedelta
+		//stepTarget = float64(*l.maxPwmChangePerCycle) * dt
```
Comment (markusressel) [inline internal/control_loop/direct.go:42]: I have removed this code for now, and I am not sure if we need it.
The PID Control Loop requires the timedelta between cycles to work properly, but I am not so sure about the Direct Control Loop. It could just as well be a feature of this type of Control Loop that it does **not** account for variations in timing.

@jwefers What is your use-case for this? Do you think its fine as is or do we need to think about the "passed time since the last cycle" in a "direct" control loop?

**Comment by markusressel** [comment]
To avoid having this issue still in production, i will merge this PR now.
Still, I am not 100% sure if the new implementation is what we want and need.
@jwefers If you can spare the time, please come back to this via this PR or the related Issue to comment, thx.
