### PR TITLE
separate pwmMap and setPwmToGetPwmMap

### LINKED ISSUE #371: `pwmMap` breaks "third party" check logic
**Describe the bug**
I have put some thought into the whole `pwmMap` thing again and I think there is still an issue with how its currently used.

> this is not desired pwm -> reported pwm, but just testing if a pwm value can be set at all?

Was actually hinting at that, as this is the way the `pwmMap` is currently automatically populated when it is not specified manually. The issue is, that this mapping is then used when applying a curve value (which is always in [0..255] range) to the fan range (which might be in some other range), which doesn't always make sense.

F.ex.: When I set a PWM of `5` to my GPU, it will report back with a PWM value of `6`. Don't ask me why, it just does. The automatically detected `pwmMap` would detect this and store `5 -> 6` in it. Now when the fan controller gets a curve value of `5`, it wants to set a PWM value of `5` to the fan, but the `pwmMap` is used and maps it to `6` instead. However, applying the map in that case is actually wrong, because setting value of `6` will result in a reported PWM value of `7`! which results in the "third party" detection springing into action on every single controller loop, as fan2go successfully confused itself.

So... I think there is a mixup of how the `pwmMap` is computed and how its used/applied in the controller logic. The computation actually creates the "desired pwm -> reported pwm" map you mentioned, but thats not what is actually needed, at least not for controlling the fan. We don't really care what PWM value is reported by the fan, we only care about our internal value range, which is always in `[0..255]`. It might be missing some values, and it might be capped at the top and bottom, but the scale is always `[0..255]`.

The current automatic computation algorithm can still be used for detecting values that yield the same result (maybe setting `4` and setting `5` both yield a reported value of `6`).

So the easy fix would be to simply not apply the `pwmMap` when controlling the fan. This would prevent the issue explained in the example above. **However** the `pwmMap` is also currently already used by people to change what values are actually set by the fan controller.

**To summarize**

I think there are two different use-cases that we need to cover that cannot both make use of the `pwmMap` alone in the same way to work.

1. We want to be able to change what value `X` is written to the PWM of a fan, based on a map. F.ex. if a fan only supports setting `[1,2,3]`, we need to map the `[0..255]` range to `[1,2,3]` somehow.
2. We want to know what PWM value `Y` is reported by the fan after writing a PWM value `X`. F.ex. setting a value of `5` might yield `6` after reading. **Crucially this not the same as in the first use-case**, as in that case setting a value of `255` might yield a value of `3`, but it could also be that setting a value of `3` yields a value of `3`, and everything above just doesn't work (throws error or whatnot). Yet, for mapping our internal range to the supported range of the fan, we cannot only use `1 -> 1, 2 -> 2, 3 -> 3` as this would result in all curve values >= 3 leading to full fan power, which is obviously not the desired behavior.

We need a clear and concise definition of what its supposed to do and be used for, then we need to implement a distinction for these two use-cases and provide a migration path (if necessary).

**Additional context**
See #358

### PR DESCRIPTION
**Pull request by markusressel**
fixes #371 

relates to #358

### CODE REVIEW

File: internal/controller/controller.go [hunk 1]
```diff
@@ -65,7 +66,38 @@ type DefaultFanController struct {
...
 	targetValuesWithDistinctPWMValue []int
-	// a map of setPwm(x) -> getPwm() for x in [0..255] for the controlled fan
+
+	// a map of setPwm(x) -> getPwm() = Y for x in [0..255] for the controlled fan
+	// this map is used to know what pwm value Y will be reported by the fan
+	// after applying a certain pwm value x to it. This is necessary
+	// because some fans do not work in the internal value range of [0..255] expected by fan2go,
+	// but rather in a different range, e.g. [0..100] or [0..255] with some values missing, yet still
+	// require the value that is set to be in the range of [0..255].
+	// Don't ask me why, hardware drivers are weird.
```
Comment (DanielGibson) [inline internal/controller/controller.go:76]: Is there really hardware that uses a different range of values for reading PWM and writing it?
If a PWM only takes values between 0 and 100, I'd expect it to also return values between 0 and 100, everything else seems super-broken.

In my limited experience, for nvidia it's consistent, for my framework laptop's fan controller one can only write PWM (0..100, everything else seems to be clamped), not read it, but I'm sure if the kernel module gets improved PWM support that also returns the current "fan duty", it will be consistent with what has been written

Comment (markusressel) [reply internal/controller/controller.go:76]: Well, my AMD RX6700 XT disagrees :shrug: :rofl: 

The underlying issue is again a conversion between [0..255] and "percent" (or [0..100]).
But instead of "denying" values that can not be mapped to a percentage value, the driver simply "rounds" it internally and reports something else.

Of course there are two options to deal with this:

1. Do not even try to set values that don't fall into the actually supported value range
2. Do allow setting values that will be rounded and be aware, that the resulting value will not be the same as the one that has been set.

The first one would be preferred, but is difficult to detect.
The second one is cumbersome, but always works.

Comment (DanielGibson) [reply internal/controller/controller.go:76]: Also, as far as I understand, that mapping comes from writing values and reading (potentially different) values back and then mapping one to the other if they're not the same.

But how do MinPWM and MaxPWM affect all this?
On my laptop, where I set MinPWM 12 (or so) and MaxPWM 100 I observed that
1. no PWM values could be read back, according to `fan init` messages fan2go then assumes that the mapping is 1-to-1 (which seems sane)
2. If the fan-curve said to set 12, it set 16 (IIRC) instead

So it must have done *something* based on Min/Max PWM alone

Comment (markusressel) [reply internal/controller/controller.go:76]: > Is it just +/- 2 or so

Yes, pretty much. It still is in [0..255], it just doesn't use all values in that range.

> But how do MinPWM and MaxPWM affect all this?

"All this" is a bit too generic for me to answer properly, but:
The value of a curve is applied to [MinPWM..MaxPWM] with linear interpolation in between.
The rounding issue mentioned above has no effect on any of this, it does throw of the sanity checks fan2go does (well with the new map it doesn't anymore), but it is still controlled properly. A fan that can only operate in [0..100] would require a `pwmMap` that specifies how to map [0..255] to [0..100] to operate correctly. If this cannot be detected automatically, it must be provided in the config of the relevant fan. This is currently pretty cumbersome, but a way to improve this was recently discussed in #363 .
